server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: http://usuario-service:8083
          predicates:
            - Path=/usuarios/**

        - id: sala-service
          uri: http://sala-service:8084
          predicates:
            - Path=/salas/**

        - id: reserva-service
          uri: http://reserva-service:8085
          predicates:
            - Path=/reservas/**
