server:
  port: 8085

spring:
  application:
    name: reserva-service
  datasource:
    url: jdbc:postgresql://db-reserva:5432/reserva_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
